### ISSUE TITLE
Opps an error occurred in your configuration. If you're in prod try cache:warmup

### ISSUE THREAD

**Issue by xocoatzin** [symfony2admingenerator/AdmingeneratorGeneratorBundle#121]
I have been trying to install AdmingeneratorBundle on my Symfony2 project, but after installation and set up i got a screen with the following message:

Opps an error occurred in your configuration. If you're in prod try cache:warmup

I followed the instructions on this Issue report:
https://github.com/cedriclombardot/AdmingeneratorGeneratorBundle/issues/74

But i still have this message appearing.

My directory structure is:

src
- Max4
  ---- TelemetrixBundle

First i set up the admin using:  php app/console admin:setup
Second i generated an admin on my current bundle using: php app/console admin:generate-admin

And i ended with the generated classes on my bundle.

The generator.yml I'm using is:

```
generator: admingenerator.generator.doctrine
params:
  model: Max4\TelemetrixBundle\Entity\Usuario
  namespace_prefix: Max4
  bundle_name: TelemetrixBundle
  fields: ~
```

Is there something wrong with this procedure or the configuration?

Thanks.
