### ISSUE TITLE
Translating list column headers

### ISSUE THREAD

**Issue by ioleo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#191]
Is there a way to translate these:

``` yaml

builders:
  list:
    params:
      title: Lista wykonawców
      display: [ id, name ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
```

The column headers are "Id" and "Name". I'd like to translate them for example to "My Super ID" and "My Custom Name".
