### ISSUE TITLE
Delete action not working - error unrecognized field

### ISSUE THREAD

**Issue by ioleo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#197]
Hello,
## Problem

Getting error: **Unrecognized field: disc_no** when trying to delete Album.
## Strange is that...

If I select this album and execute Batch delete - it works (entity deleted).

But when i try to just click "delete" icon in Actions - I get this error.
## Schema

``` php
Album has:
 - id
 - name
 - songs (OneToMany)

    /**
     * @ORM\OneToMany(targetEntity="Song", mappedBy="album", cascade={"all"}, orphanRemoval=TRUE)
     */



Song has:
 - id
 - title
 - discNo @ORM\Column(type="integer", name="disc_no", nullable=TRUE)
 - trackNo @ORM\Column(type="integer", name="track_no", nullable=TRUE)
```
## Generators

Song:

``` yaml
generator: admingenerator.generator.doctrine
params:
  model: Avocode\TestBundle\Entity\Song
  namespace_prefix: Avocode
  bundle_name: TestBundle
  fields: 
    title:
      label: Title
    discNo:
      label: Disc
      help: Disc number
    trackNo:
      label: Track
      help: Track number

builders:
  list:
    params:
      title: Lista utworów
      display: [ title, discNo, trackNo ]
      actions:
        new: ~
      batch_actions:
        delete: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Nowy utwór
      display: [ title, discNo, trackNo ]
      actions:
        list: ~
  edit:
    params:
      title: Edytuj utwór "{{ Song.title }}"
      display: [ title, discNo, trackNo ]
      actions:
        list: ~
  delete:
    label: Delete?
    confirm: Are you sure to delete {{ Song.title }} ?
```

Album:

``` yaml
generator: admingenerator.generator.doctrine
params:
  model: Avocode\TestBundle\Entity\Album
  namespace_prefix: Avocode
  bundle_name: TestBundle
  fields:
    songs:
      formType: collection
      extras:
        new_label: New song # By default is an autoincrement
      addFormOptions:
        type: \Avocode\TestBundle\Form\Type\EmbedsongType

builders:
  list:
    params:
      title: Lista albumów
      display: ~
      actions:
        new: ~
      batch_actions:
        delete: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Nowy album
      display: [ name, songs ]
      actions:
        list: ~
  edit:
    params:
      title: Edytuj album "{{ Album.name }}"
      display: [ name, songs ]
      actions:
        list: ~
  delete:
    label: Delete?
    confirm: Are you sure to delete {{ Album.name }} ?
```

Any ideas whats wrong?
