### ISSUE TITLE
Introducing nested collections

### ISSUE THREAD

**Issue by ioleo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#200]
### Introducing nested collections

Consider this schema:

``` yaml
CONTINENT:
 - name
 - countries (OneContinentToManyCountries)

COUNTRY:
 - name
 - cities (OneCountryToManyCities)
 - continent (ManyCountriesToOneContinent)

CITY:
 - name
 - country (ManyCitiesToOneCountry)
```
### Task: add a country and 5 cities

This is no problem, if you define your generator like this:

``` yaml
generator: admingenerator.generator.doctrine
params:
  model: Avocode\TestBundle\Entity\Country
  namespace_prefix: Avocode
  bundle_name: TestBundle
  i18n_catalog: AvocodeTestBundle
  fields:
    id:
      label:  ID
    name:
      label:  country.name.label
      help:   country.name.help
    cities:
      formType: collection
      extras:
        new_label: country.cities.new.label
      addFormOptions:
        type: \Avocode\TestBundle\Form\Type\Country\EmbedCityType
        allow_add: true
        allow_delete: true
        by_reference: false
```

And EmbedCityType:

``` php
# src: Avocode\TestBundle\Form\Type\Country\EmbedCityType.php

namespace Avocode\TestBundle\Form\Type\Country;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class EmbedCityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {        
        $builder
            ->add('name', 'text')
        ;
    }

    public function getName()
    {
        return 'embed_city';
    }

    public function getDefaultOptions(array $options){
        return array('data_class' => 'Avocode\TestBundle\Entity\City');
    }
}
```
### How to do this task:

add a new continent (South America) with 2 counties (Brazil, Argentina) with 3 biggest cities each country (**for Brazil:** _São Paulo, Rio de Janeiro, Salvador_; **for Argentina:** _Buenos Aires, Córdoba, Rosario_)
