### ISSUE TITLE
How to use virtual fields in Filters and Scopes?

### ISSUE THREAD

**Issue by ioleo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#239]
### Category entity has:

**fields:**
- id
- name
- parent
- children

**methods:**
- getters and setters for id, name, parent and children
- getNestingLevel()

> **returns an integer** iterates through parents tree until `parent === null` (root node) and returns category nesting level
- countChildren()

> **returns an integer** returns $this->getChildren()->count()
### What I want to do?

I want to:
- be able to filter by nesting level
- add scopes like:
  - **All** (no filters), 
  - **Root** (`nestingLevel == 0`), 
  - **Leaf** (`countChildren == 0`)
### Generator.yml configuration

``` yaml
generator: admingenerator.generator.doctrine
params:
  model: Acme\TestBundle\Entity\Category
  namespace_prefix: Acme
  bundle_name: TestBundle
  fields:
    id:
      label:  ID
    name:
      label:  Name
    parent:
      label:  Parent
    children:
      label:  Children
    nestingLevel:
      label:  Nesting level
      getter: nestingLevel
    countChildren:
      label: Children total
      getter: countChildren
builders:
  list:
    params:
      scopes:
        group_1: 
          All: ~
          Root: 
            filters: 
              nestingLevel: 0
          Leaf: 
            filters: 
              countChildren: 0
      title: Category list
      display: [ id, name, parent, children, nestingLevel, countChildren ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ name, nestingLevel, countChildren ]
```
### Errors

Unfortunately this throws errors:

```
An exception has been thrown during the rendering of a template ("The dbType "virtual" is only for list implemented (column "nestingLevel")") in ListBuilderAction.php.twig at line 121.
```

or if I add

``` yaml
#...
    nestingLevel:
      # ...
      dbType: integer
#...
```

Then I get error

```
An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 64 near 'nestingLevel': Error: Class Acme\TestBundle\Entity\Category has no field or association named nestingLevel") in "AcmeTestBundle:CategoryList:index.html.twig".
```
## Is there a way to do it?

I found that [filters configuration](http://symfony2admingenerator.org/cheat-sheet/generator.html#filters-configuration) section is missing in the docs.
## If not..

Where should I digg to add/enable virtual fields for filters and scopes?
