### ISSUE TITLE
Require generating another generator.yml

### ISSUE THREAD

**Issue by ioleo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#271]
In some cases it would be useful to provide parameter for generator.yml to force generate other generator before this one.

Example `Category-generator.yml`:

``` yaml
generator: admingenerator.generator.doctrine
params:
  model: Acme\CatalogueBundle\Entity\Category
  namespace_prefix: Acme
  bundle_name:  CatalogueBundle
  fields:
    products:
      formType: collection
      addFormOptions:
        type: \Acme\CatalogueBundle\Form\Type\Product\EditType
```

This will throw error, becouse cache for `Product-generator.yml` has not been created (not generated). To make this work right now I have to navigate to _Product list action_ to force Admingenerator generating code for Product.
### Require parameter

``` yaml
generator: admingenerator.generator.doctrine
require:
 - Acme\CatalogueBundle\Resources\config\Product-generator.yml
params:
  model: Acme\CatalogueBundle\Entity\Category
  namespace_prefix: Acme
  bundle_name:  CatalogueBundle
  fields:
    products:
      formType: collection
      addFormOptions:
        type: \Acme\CatalogueBundle\Form\Type\Product\EditType
```

The require parameter would point Admingenerator that before generating code for this generator it has to generate some other generator first.

> In my example, if user enters **CATEGORY** generated page I'd like to tell _Admingenerator_ to generate **Product-generator.yml** first (becouse I use a formType from that generator).
