### ISSUE TITLE
Error in Edit template

### ISSUE THREAD

**Issue by ioleo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#275]
I'm getting error:

> Key "name" in object (with ArrayAccess) of type "Symfony\Component\Form\FormView" does not exist in "AvocodeCatalogueBundle:PropertyEdit:index.html.twig"

When going to Property `edit action`. What is insteresting is that `new action` works flawlessly.

But `new action` template is the same as `edit action` template! They only have diffrent controllers. I tried to find the diffrence in controller, but I couldn't find any!

I don't really understand why this error happens.

I know the error is caused by these three

``` html+django
{{ echo_twig("form_errors(form['" ~ field ~ "'])") }}
{{ echo_twig("form_label(form['" ~ field ~ "'])") }}
{{ echo_twig("form_widget(form['" ~ field ~ "'])") }}
```

But the same are used in `new action` template and cause no error there. WTF is wrong?

> Useing `feat-twitter-theme` branch, but the same happens when I switched to master branch

Property entity is very simple:
- id
- name (string, 255, not nullable)
- value (string, 255, nullable)
- product (many-to-one relation, many properties to one product, mapped by product_id )
- standard getters and setters

``` yaml
generator: admingenerator.generator.doctrine
params:
  model: Avocode\CatalogueBundle\Entity\Property
  namespace_prefix: Avocode
  bundle_name:  CatalogueBundle
  i18n_catalog: CatalogProperty
  fields:
    id:
      label:    label.id
    name:
      label:    label.name
    value:
      label:    label.value
    product:
      label:    label.product
builders:
  list:
    params:
      title:    title.list
      display:  [ id, name, value ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display:  [ name, value ]
  new:
    params:
      title:    title.new
      display:  
        "NONE":  [ [ name , value ] ]
      actions:
        list: ~
  edit:
    params:
      title:    title.edit|{ Property.name }|
      display:  
        "NONE":  [ [ name , value ] ]
      actions:
        list: ~
  delete: ~
```
