### ISSUE TITLE
ServiceNotFoundException: You have requested a non-existent service "admingenerator.generator.doctrine".

### ISSUE THREAD

**Issue by DavidParkin** [symfony2admingenerator/AdmingeneratorGeneratorBundle#336]
Installed using "minimum-stability": "dev" in order to resolve dependencies. Generate file, looks ok, but I get the above message. It has something to do with the generate.yml. Move or delete that file and message goes away. 
File looks like this except that - title: "You're viewing the object \"%object%\"|{ %object%: YourModel.title }|" was generated without closing ".

``` yaml
generator: admingenerator.generator.doctrine
params:
  model: David\BaseBundle\Entity\FeedItem
  namespace_prefix: David
  bundle_name: BaseBundle
  fields: ~
builders:
  list:
    params:
      title: List for BaseBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New object for BaseBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: "You're editing the object \"%object%\"|{ %object%: YourModel.title }|"
      display: ~
      actions:
        list: ~
  show:
    params:
      title: "You're viewing the object \"%object%\"|{ %object%: YourModel.title }|"
      display: ~
      actions:
        list: ~
        new: ~
  delete: ~
```

Is this sufficient for someone to help? If the answer is not obvious then perhaps I could get some pointers to help me debug it?
