### ISSUE TITLE
Where is my "Save" button?

### ISSUE THREAD

**Issue by ioleo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#351]
As of a2cb10c8f80a364e472f8346d51d75f74aea571b the save action is no longer added by default.

To add save action simply edit your `generator.yml` and add `save: ~`:

``` yaml
actions:
  save: ~
  list: ~
```

This allows you to use other submit actions instead of the default one:

``` yaml
actions:
  save: ~
  save-and-add: ~
  save-and-list: ~
  show: ~
  list: ~
```
