### ISSUE TITLE
Commit  a2cb10c8f80a364e472f8346d51d75f74aea571b does not make any sense !

### ISSUE THREAD

**Issue by alex-ception** [symfony2admingenerator/AdmingeneratorGeneratorBundle#357]
'Not sur this is really that commit, but according to the description, it seems to be this one : a2cb10c8f80a364e472f8346d51d75f74aea571b.

This commit override "actions" sections in generators, and is not showing any "save" button if overrided.

To be clear, here is a part of my generator file :

``` yaml
  edit:
    params:
      actions:
        list: ~
```

Before this commit, I had a save button displayed, but since, I have to force it in the file to be displayed, and it does not make any sense at all : 

``` yaml
  edit:
    params:
      actions:
        list: ~
        save: ~
```

Thanks. I hope my message is understandable enough.
