### ISSUE TITLE
timestamp db type (postgresql)

### ISSUE THREAD

**Issue by suncat2000** [symfony2admingenerator/AdmingeneratorGeneratorBundle#36]
How to use db type timestamp for dates and times. I have an error in its use.

_Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The dbType "timestamp" is not yet implemented") in "ListBuilderAction.php.twig" at line 71._

My.orm.yml (datetime_create)

```
Admin\MyBundle\Entity\Text:
type: entity
table: texsts
id:
    id:
        type: integer
        generator: { strategy: AUTO }
fields:
    is_published:
        type: boolean
    datetime_create:
        type: timestamp
```

....
