### ISSUE TITLE
Non-standard bundle namespace not supported

### ISSUE THREAD

**Issue by watermanio** [symfony2admingenerator/AdmingeneratorGeneratorBundle#376]
The routing does not seem to work with non-standard bundle names. 

Eg. My bundle is Cg\CrmBundle, but this only seems to support Cg\CgCrmBundle.

```
 Bundle namespace: Cg\CrmBundle
 Model name [YourModel]: Interest

 In your code, a bundle is often referenced by its name. It can be the
 concatenation of all namespace parts but it's really up to you to come
 up with a unique name (a good practice is to start with the vendor name).
 Based on the namespace, we suggest CgCrmBundle.
```

The routing is added correctly:

``` yaml
CrmBundle_admin_crm_bundle_interest:
    resource: "@CrmBundle/Controller/Interest/"
    type:     admingenerator
    prefix:   /admin/crm_bundle/interest
```

But I get an error if I go to that route:

```
Cannot load resource "@CgCrmBundle/Controller/Interest/". Make sure the "CgCrmBundle" bundle is correctly registered and loaded in the application kernel class. 
```

So some how it's still looking for the CgCrmBundle, not my shortened CrmBundle.

I'd edit and PR, but not sure where to start looking...
