### ISSUE TITLE
[Twig_Error_Runtime] ListBuilderAction.php.twig in error

### ISSUE THREAD

**Issue by lionelbzv** [symfony2admingenerator/AdmingeneratorGeneratorBundle#383]
I cannot use my project since a "composer update" generates this problem:

<code>
An exception has been thrown during the rendering of a template
("Warning: strtr() expects parameter 1 to be string, array given in 
/.../vendor/doctrine/inflector/lib/Doctrine/Common/Inflector/Inflector.php line 214") 
in "ListBuilderAction.php.twig" at line 62
</code>

composer.json:

``` yaml
{
    "name": "my-project",
    "description": "My Project",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "repositories": {
        "phing": {
            "type": "pear",
            "url": "http://pear.phing.info"
        },
        "phingGit": {
            "type": "package",
            "package": {
                "name": "phing/phing",
                "version": "master",
                "source": {
                    "url": "git://github.com/Xosofox/phing.git",
                    "type": "git",
                    "reference": "master"
                }
            }
        },
        "TypehintableBehavior": {
            "type": "package",
            "package": {
                "name": "TypehintableBehavior",
                "version": "master",
                "source": {
                    "url": "git://github.com/willdurand/TypehintableBehavior.git",
                    "type": "git",
                    "reference": "master"
                }
            }
        }
    },
    "require": {
        "php": ">=5.3.3",

        "symfony/symfony": "2.2.*",

        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",

        "twig/extensions": "*",

        "symfony/assetic-bundle": "2.1.*",
        "symfony/swiftmailer-bundle": "2.2.*",
        "symfony/monolog-bundle": "2.2.*",

        "sensio/distribution-bundle": "2.2.*",
        "sensio/framework-extra-bundle": "2.2.*",
        "sensio/generator-bundle": "2.2.*",

        "jms/security-extra-bundle": "1.4.*",
        "jms/di-extra-bundle": "1.3.*",

        "friendsofsymfony/user-bundle": "*",

        "propel/propel-bundle": "1.2.*",
        "craftyshadow/propel-equalnest-behavior": "dev-master",

        "phing/phing": "2.4.14",

        "TypehintableBehavior": "master",

        "white-october/pagerfanta-bundle": "dev-master",

        "ensepar/html2pdf-bundle" : "dev-master",

    "knplabs/knp-menu-bundle": "dev-master",

    "cedriclombardot/twig-generator": "dev-master",
    "cedriclombardot/admingenerator-generator-bundle": "dev-master",
    "cedriclombardot/admingenerator-user-bundle": "dev-master",

        "liip/imagine-bundle": "dev-master",

        "genemu/form-bundle": "2.1.*"
    },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "minimum-stability": "dev",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "symlink",
        "branch-alias": {
            "dev-master": "2.2-dev"
        }
    }
}

```
