### ISSUE TITLE
Upload widget with symfony 2.2

### ISSUE THREAD

**Issue by denys281** [symfony2admingenerator/AdmingeneratorGeneratorBundle#400]
Upload widget don't work with symfony 2 .2. 

I have Exception:

``` php
Catchable Fatal Error: Argument 2 passed to Symfony\Component\Form\Extension\Core\EventListener\ResizeFormListener::__construct() must be of the type array, object given, called in /home/dan/WEB/www/officebud-dev.my/vendor/cedriclombardot/admingenerator-generator-bundle/Admingenerator/GeneratorBundle/Form/Type/DoctrineORM/UploadType.php on line 50 and defined in /home/dan/WEB/www/officebud-dev.my/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php line 48 
```

My configuration: 

``` yml
 gallery:
        label:            Зображення
        dbType:           collection
        formType:         upload
        addFormOptions:
          nameable:         name
          editable:         [name, description]
          type:             \Webmil\FrontendNewsBundle\Form\NewsGalleryType
          maxFileSize:                5000000
          minFileSize:                1000
          acceptFileTypes:            /(\.|\/)(gif|jpe?g|png)$/i
          previewSourceFileTypes:     /^image\/(gif|jpeg|png)$/
          previewSourceMaxFileSize:   250000
          previewMaxWidth:            100
          previewMaxHeight:           100
          previewAsCanvas:            true
          prependFiles:               false 
          allow_delete:               true
          options:
            data_class:     Webmil\FrontendNewsBundle\Entity\NewsGallery
```

It all works with symfony 2.1
