### ISSUE TITLE
single_upload widget : I cannot succeed using it

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/AdmingeneratorGeneratorBundle#406]
Hello,

I also have some problems with single_upload. Here is my code:

``` yaml
vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /upload/images/products
            upload_destination: %kernel.root_dir%/../web/upload/images/products
            namer: vich_uploader.namer_uniqid
            inject_on_load:       true
```

``` yaml
admingenerator_generator:
    thumbnail_generator: null
```

``` php
/**
 * Product
 * @Vich\Uploadable
 */
class Product
{
...
/**
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="picture")
     *
     * @var File pictureFile
     */
    protected $pictureFile;

    /**
     * @var string
     */
    private $picture = null;

    public function getPictureFile()
    {
        return $this->pictureFile;
    }

    public function setPictureFile(File $file)
    {
        $this->pictureFile = $file;

        return $this;
    }

    /**
     * Set picture
     *
     * @param string $picture
     * @return Product
     */
    public function setPicture($picture)
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * Get picture
     *
     * @return File
     */
    public function getPicture()
    {
        return $this->pictureFile; // Also tried with $this->picture, but form could'nt be correctly rendered in edit view
    }
...
}
```

``` yaml
picture:
            label: admin.product.label.picture
            help:  admin.product.help.picture
            sortable: false
            formType: single_upload
            addFormOptions:
                data_class:     Symfony\Component\HttpFoundation\File\File
```

1- When my object is saved, entry in DB is temp file path;
2- File is not moved in my destination directory;

Any idea why is this happening?

Thank you,
