### ISSUE TITLE
filters section does not accept dbType overriding

### ISSUE THREAD

**Issue by ghost** [symfony2admingenerator/AdmingeneratorGeneratorBundle#410]
Hi,
I may be missing something, but it seems to me it's not possible to override dbType parameter under the "filters" section.

``` yaml
generator: admingenerator.generator.propel
params:
  model: Acme\DemoBundle\Model\Foo
  namespace_prefix: Acme
  bundle_name: DemoBundle

builders:
  list:
    params:
      title: foo.list.title
      display: [name, gender, description]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
      max_per_page: 50
  filters:
    params:
      display: [gender]
      fields:
        gender:
          dbType: VARCHAR
```

This will throw a The dbType "virtual" is not yet implemented (column "gender") if gender column is not part of the Foo object, or won't override the filter behavior in case gender is a concrete column.
To make the gender filter fields having a different dbType, we need to change dbType in the top "params" section

``` yaml
generator: admingenerator.generator.propel
params:
  model: Acme\DemoBundle\Model\Foo
  namespace_prefix: Acme
  bundle_name: DemoBundle
  fields:
    gender:
      dbType: VARCHAR
```

Thus leading to override field at top level, which can conflicts with other actions in list/edit/new
Moreover documentation is not clear about how far fields section configuration may be overriden in list/filters/edit/new sections
