### ISSUE TITLE
Disabling sorting on a column

### ISSUE THREAD

**Issue by ghost** [symfony2admingenerator/AdmingeneratorGeneratorBundle#411]
Can we imagine to disable automatic sorting on a column

``` yaml
  list:
    params:
      title: foo.list.title
      display: [id, lastname, firstname]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
      fields:
        firstname: 
          sort_on: ~ # or false
```

Some sorting are not relevant and may be removed for a more precise user experience
The current behavior is to ignore `sort_on` if a false/null value is provided
