### ISSUE TITLE
Twig_error_Runtime: item display for "" does not exist in "ListBuilderAction.php.twig" at line 11

### ISSUE THREAD

**Issue by jeronimoc** [symfony2admingenerator/AdmingeneratorGeneratorBundle#420]
Hi, im trying to configure de admingeneratorbundle and it throws me this error.

```
the generator.yml is this:
generator: admingenerator.generator.doctrine
params:
    model: Miam\MiamBundle\Entity\ingredient
    namespace_prefix: Miam
    bundle_name: MiamBundle
    fields:
        id:
        name:
        description:
builders:
    list:
        params:
            title: "Configurar ingredientes"
            display: [id, name]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    new:
        params:
            title: "Nuevo ingrediente"
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "editar ingrediente"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "mostrar ingrediente"
            display: ~
            actions:
                list: ~
                new: ~
            object_actions:
    delete: ~
```

Let me know if you need something more to know where the problem it can be.
The entity is in yml configuration.
Sorry for my bad english, thanks!
