### ISSUE TITLE
Wrong action route generated in template

### ISSUE THREAD

**Issue by buxx** [symfony2admingenerator/AdmingeneratorGeneratorBundle#456]
Since last update with "cedriclombardot/admingenerator-generator-bundle": "2.1.*@dev" my route action like to "lost" parameter.

My action:

```
  object_actions:
    accept:
      route: Muzich_AdminBundle_Moderate_tag_accept
      params:
        pk: "{{ Tag.id }}"
      icon: icon-ok-sign
      class: moderate_accept
```

What template looks like:

```
<button class="moderate_accept" data-action="{{ path("Muzich_AdminBundle_Moderate_tag_accept") }}"rel="toolt ...
<i class="icon-ok-sign"></i>
</button>
```

Route Muzich_AdminBundle_Moderate_tag_accept need "pk" (with id), so an error is launched.
