### ISSUE TITLE
Jquery field validation 

### ISSUE THREAD

**Issue by denys281** [symfony2admingenerator/AdmingeneratorGeneratorBundle#464]
When I have field config for example:

``` yaml
video:
        label: Відео
        formOptions:
        attr:
          class: input-xxlarge  
```

I get for this field html5 validation **required="required"**,  and I can't remove this. And in my entity I set to this field nullable=true.

When I have config:

``` yaml
video:
        label: Відео
```

It is all ok.
