### ISSUE TITLE
Upload widget bug

### ISSUE THREAD

**Issue by denys281** [symfony2admingenerator/AdmingeneratorGeneratorBundle#466]
My config:

``` yaml
      gallery:
        label:            Зображення
        dbType:           collection
        formType:         upload
        addFormOptions:
          nameable:         name
          editable:         [name]
          type:             \Bastion\FrontendNewsBundle\Form\NewsGalleryType
          acceptFileTypes:            /(\.|\/)(gif|jpe?g|png)$/i
          previewSourceFileTypes:     /^image\/(gif|jpeg|png)$/
          previewMaxWidth:            100
          previewMaxHeight:           100
          previewAsCanvas:            true
          prependFiles:               false 
          allow_delete:               true
          options:
            data_class:     Bastion\FrontendNewsBundle\Entity\NewsGallery
```

All works perfect. But when I remove :  

``` yaml
          editable:         [name]
```

I have:
1. When I upload my photos first time it is all ok. 
2. Than when I update my entry, all my photos  **_disappears**_.
