### ISSUE TITLE
Command admin:setup fails

### ISSUE THREAD

**Issue by willdurand** [symfony2admingenerator/AdmingeneratorGeneratorBundle#49]
The command says:

```
Edit config.yml and configure the section admingenerator_generator like that :
admingenerator_generator:
    base_admin_template: AdmingeneratorActiveAdminThemeBundle::base_admin_assetic_less.html.twig
    use_propel: yes
    use_doctrine_orm: no
    use_doctrine_odm: no
```

If I do that, then I get:

```
[Symfony\Component\Config\Definition\Exception\InvalidTypeException]                                  
Invalid type for path "admingenerator_generator.use_doctrine_orm". Expected boolean, but got string.  
```

That's because you've configured boolean attributes. You should generate `true` instead of `yes`, `false` instead of `no`.

William
