### ISSUE TITLE
Translation syntax is not working for actions

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/AdmingeneratorGeneratorBundle#497]
The translation syntax from generator is not correctly handled for:
- confirm messages on actions
- label/title on actions

Because of this, some configurations like:

``` yml
object_actions:
    my_action:
        confirm: Are you sure you want to delete {{ Model.name }}?
```

neither

``` yml
object_actions:
    my_action:
        confirm: "Are you sure you want to delete %name%?|{ %name%: Model.name }|"
```

are not allowed.
