### ISSUE TITLE
List sorting collection problem

### ISSUE THREAD

**Issue by ioleo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#499]
When sorting by `groups` I'm getting

``` console
An exception has been thrown during the rendering of a template 
("[Semantical Error] line 0, col 62 near 'groups ASC': 
Error: Invalid PathExpression. StateFieldPathExpression or 
SingleValuedAssociationField expected.") in 
"MySecurityBundle:UserList:index.html.twig".
```

My groups field configuration:

``` yaml
groups:
    label:            Groups
    formType:         collection
    addFormOptions:
        type:           entitypicker
        widget:         table
        allow_add:      true
        allow_delete:   true
        by_reference:   false
        options:
            label:        New group
            class:        Vipharm\SecurityBundle\Entity\Group
            builder:      { name: name }
            matcher:      item.name
            primaryKey:   id
```

TODO: check why this is happening
