### ISSUE TITLE
[Security] Security check is not generated in PHP code

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/AdmingeneratorGeneratorBundle#531]
Given the following generator:

``` yml
generator: admingenerator.generator.doctrine
params:
    ...
    object_actions:
        ...
        toggleIsActive:
            credentials: 'hasRole("ROLE_ACCOUNT")'
            ...
    batch_actions:
        toggleIsActive:
            credentials: 'hasRole("ROLE_ACCOUNT")'

builders:
    actions:
        params:
            object_actions:
                delete: ~
                toggleIsActive: ~
            batch_actions:
                toggleIsActive: ~

    list:
        params:
            ...
            object_actions:
                show: ~
                edit: ~
                delete: ~
            batch_actions:
                toggleIsActive: ~
    ...
```

The generated code will not contain the security check necessary code.
