### ISSUE TITLE
Unable to generate a URL for the named route "Acme_AdminBundle_User_object"

### ISSUE THREAD

**Issue by Matzz** [symfony2admingenerator/AdmingeneratorGeneratorBundle#559]
After claring cache I get exception:

```
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "Acme_AdminBundle_User_object" as such route does not exist.") in "AcmeAdminBundle:UserList:index.html.twig".
```

generated template:

``` twig
{% block td_list_object_actions_delete %}


{% spaceless %}
<a  class="btn btn-mini " href="{{ path("Acme_AdminBundle_User_object", { pk: User.id, action: 'delete' }) }}" 
data-original-title="{% trans from "Admingenerator" %}action.object.delete.label{% endtrans %}" rel="tooltip" data-confirm="{% trans from "Admingenerator" %}action.object.delete.confirm{% endtrans %}"  data-csrf-token="{{ path("Acme_AdminBundle_User_object", { pk: User.id, action: 'delete' })|csrf_token }}" ><i class="icon-remove"></i></a>
{% endspaceless %}

{% endblock td_list_object_actions_delete %}
```

User-generator.yml

``` yaml
generator: admingenerator.generator.doctrine
params:
    i18n_catalog: messages
    model: Acme\UserBundle\Entity\User
    namespace_prefix: Acme
    bundle_name: AdminBundle

builders:
    list:
        params:
            title: "List"
            display:
              - id
              - username
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display:
              - username
    new:
        params:
            title: "New"
            display:
              - username
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Edit"
            display:
              - username
            actions:
                save: ~
                show: ~
                list: ~
    show:
        params:
            title: "Show"
            display:
              - id
              - username
            actions:
                edit: ~
                list: ~
                new: ~
    delete: ~
```
