### ISSUE TITLE
Tabs are not handled in show views

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/AdmingeneratorGeneratorBundle#567]
In generated show views, tabs are not handled (just making multiple fieldsets).
Example:

``` yaml
    show:
        params:
            title: "admin.newsletter.title.show|{ %name%: Newsletter.subject }|"
            tabs:
                "admin.newsletter.tab.display":
                    NONE_display: [ sentAt, subject, content ]
                "admin.newsletter.tab.recipients":
                    NONE_recipients: [ recipients ]
            actions:
                list: ~
                new: ~
```
