### ISSUE TITLE
error after composer update on generating form

### ISSUE THREAD

**Issue by alexbaron** [symfony2admingenerator/AdmingeneratorGeneratorBundle#600]
hello

I 've installed and update my composer, but now embeded form like collection or just single type doesn't work anymore.

the error : 

```
Could not load type "\MyApp\ModelBundle\Form\AdresseLivraisonClientType"
```

here is my generator (the edit part) : 

``` yaml
 edit:
        params:
            fields:

              adresseFacturation:
                label:            adresse de facturation client
                dbType:           string
                formType:         \MyApp\ModelBundle\Form\AdresseFacturationClientType

              adresseLivraison:
                label:            adresse de livraison
                dbType:           string
                formType:       \MyApp\ModelBundle\Form\AdresseLivraisonClientType

              clientsSites:
                label:            site de production
                dbType:           collection
                formType:         collection
                addFormOptions:
                  type:           \MyApp\ModelBundle\Form\ClientsSitesType
                  allow_add:      true
                  allow_delete:   true
                  by_reference:   false
                  options:
                    label:          Ajouter un site de production
                    data_class:     MyApp\ModelBundle\Entity\ClientsSites

              infosBancaire:
                label:            information bancaires
                dbType:           string
                formType:         collection
                addFormOptions:
                  type:           
                  allow_add:      true
                  allow_delete:   true
                  by_reference:   false
                  options:
                    label:          Ajouter un nouveau compte
                    data_class:     MyApp\ModelBundle\Entity\InfosBancaire

              contacts:
                label:            contacts chez le client
                dbType:           collection
                formType:         collection
                addFormOptions:
                  type:           \MyApp\ModelBundle\Form\ContactClientType
                  allow_add:      true
                  allow_delete:   true
                  by_reference:   false
                  options:
                    label:          Ajouter un nouveau contact
                    data_class:     MyApp\ModelBundle\Entity\ContactClient

              tourneesClient:
                label:            tournées du client
                dbType:           collection
                formType:         collection
                addFormOptions:
                  type:           \MyApp\ModelBundle\Form\TourneesClientType
                  allow_add:      true
                  allow_delete:   true
                  by_reference:   false
                  options:
                    label:          Ajouter une nouvelle adresse de livraison
                    data_class:     MyApp\ModelBundle\Entity\TourneeClient

              groupsClientsSites:
                  label: groupement pour le site de référence
                  formType: choice

            title: "You're editing the object \"%object%\"|{ %object%: Client.raisonSociale }|"
            display: 
              "Générale" : 
                - codeClient
                - codeService
                - raisonSociale
                - familleClient
                - groupsClientsSites
                - groupsClientsNationaux
                - clientsSites
              "Comptabilité":
                - compteCollectif
                - codeExport
                - codeReleve
                - isTVA
                - codeReglement
              "Facturation" : 
                - codeClientFacturation
                - numTvaIntracommunautaire
                - nbrFacture
                - isFactureUsine
                - isFactureEmail
                - factureEmail
                - isFactureTraitementManuel
                - escompte
                - remise
                - isSuiviStock
                - adresseFacturation
              "infos Bancaires":
                - infosBancaire
              "Commerciale" : 
                - sav
                - representant
                - contacts
              "Production" : 
                - coeffRotationStock
                - frequenceTournee
                - adresseLivraison
                - tourneesClient
              "Commentaire" : 
                - rcs
                - naf 
            actions:
                list: ~
```

and my composer : 

``` json
{
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": {"": "src/"}
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.2.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "doctrine/doctrine-migrations-bundle": "dev-master",
        "twig/extensions": "dev-master",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.2.*",
        "symfony/monolog-bundle": "2.2.*",
        "symfony/dom-crawler": "2.2.*",
        "symfony/css-selector": "2.2.*",
        "sensio/distribution-bundle": "2.2.*",
        "sensio/framework-extra-bundle": "2.2.*",
        "sensio/generator-bundle": "dev-master",
        "jms/security-extra-bundle": "1.4.*",
        "jms/di-extra-bundle": "1.3.*",
        "leafo/lessphp": "0.*",
        "leafo/scssphp": "0.*",
        "pagerfanta/pagerfanta": "dev-master",
        "white-october/pagerfanta-bundle": "dev-master",
        "cedriclombardot/admingenerator-generator-bundle": "dev-master",
        "friendsofsymfony/jsrouting-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "dev-master",
        "bmatzner/jquery-bundle": "dev-master",
        "imag/ldap-bundle": "dev-master",
        "netpositive/discriminatormap-bundle": "dev-master",
        "leafo/lessphp": "dev-master",
        "problematic/acl-manager-bundle": "dev-master",
        "avocode/form-extensions-bundle": "dev-master",
        "robloach/component-installer": "dev-master",
        "components/jquery": "1.9.*",
        "components/normalize.css": "2.*",
        "components/bootstrap-default": "2.*"
    },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "component-dir": "web/public"
    },
    "minimum-stability": "dev",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "branch-alias": {
            "dev-master": "2.2-dev"
        }
    }
}
```
