### ISSUE TITLE
Credentials in filters builder is not taked into account in all generated files

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/AdmingeneratorGeneratorBundle#607]
If we have the following generator file:

``` yaml
filters:
        params:
            ...
            fields:
                ...
                product:
                    credentials: 'hasRole("ROLE_ADMIN")'
```

FiltersType will be well generated (taking into account credentials), but templates and actions will not.

I could simply bypass this error putting the credentials on global fields definition.

But, is it possible to imagine that, for a filter, credentials could be different from related field?

I currently have a workaround solving the template issue. But I didnt' notice before how `processFilters` function is deeply linked to ListBuilder.

Do you think this is a real issue we have to fix (just to know if I have to continue my fix)?
