### ISSUE TITLE
Upgrade Help ... "save-and-add"

### ISSUE THREAD

**Issue by mikeyudin** [symfony2admingenerator/AdmingeneratorGeneratorBundle#608]
I'm attempting to upgrade to >=2.0 from an old release (not an easy feat for a semi-large application -- wish there was an easier way).    One issue I'm having is lack of documentation in the Edit Builder.  I'm trying to specify a new/edit action "save-and-add", but instead of generating the button, it's trying to generate a link based on "save-and-add" ... 

``` yaml
new:
    params:   
        actions:
            save: ~
            save-and-add: ~
            list: ~
```

throws the following exception:

```
Unable to generate a URL for the named route "MyApplication_MyBundle_MyEntity_save-and-add"
```

Is there something I am missing in the upgrade notes?  If I try "saveAndAdd: ~" it works fine, but the name of the button is incorrect "saveAndAdd" instead of "save-and-add".
