### ISSUE TITLE
error after composer update updateRouting wrong definition function

### ISSUE THREAD

**Issue by alexbaron** [symfony2admingenerator/AdmingeneratorGeneratorBundle#612]
hello,

i update my project form composer and now i've got this error.

``` php
Runtime Notice: Declaration of Admingenerator\GeneratorBundle\Command\GenerateAdminCommand::updateRouting() should be compatible with that of Sensio\Bundle\GeneratorBundle\Command\GenerateBundleCommand::updateRouting() ...
```

here is my composer

``` yml
{
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": {"": "src/"}
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.2.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "doctrine/doctrine-migrations-bundle": "dev-master",
        "twig/extensions": "dev-master",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.2.*",
        "symfony/monolog-bundle": "2.2.*",
        "symfony/dom-crawler": "2.2.*",
        "symfony/css-selector": "2.2.*",
        "sensio/distribution-bundle": "2.2.*",
        "sensio/framework-extra-bundle": "2.2.*",
        "sensio/generator-bundle": "dev-master",
        "jms/security-extra-bundle": "1.4.*",
        "jms/di-extra-bundle": "1.3.*",
        "leafo/lessphp": "0.*",
        "leafo/scssphp": "0.*",
        "pagerfanta/pagerfanta": "dev-master",
        "white-october/pagerfanta-bundle": "dev-master",
        "cedriclombardot/admingenerator-generator-bundle": "dev-master",
        "friendsofsymfony/jsrouting-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "dev-master",
        "bmatzner/jquery-bundle": "dev-master",
        "imag/ldap-bundle": "dev-master",
        "netpositive/discriminatormap-bundle": "dev-master",
        "leafo/lessphp": "dev-master",
        "problematic/acl-manager-bundle": "dev-master",
        "avocode/form-extensions-bundle": "dev-master",
        "robloach/component-installer": "dev-master",
        "components/jquery": "1.9.*",
        "components/bootstrap": "2.*",
        "components/normalize.css": "2.*",
        "components/font-awesome": "3.*",
        "components/bootstrap-default": "2.*"
    },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "component-dir": "web/public"
    },
    "minimum-stability": "dev",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "branch-alias": {
            "dev-master": "2.2-dev"
        }
    }
}
```
