### ISSUE TITLE
Add possibility to pass object properties to action route

### ISSUE THREAD

**Issue by Matzz** [symfony2admingenerator/AdmingeneratorGeneratorBundle#637]
I want add "edit" action to "show" view (to bottom menu). If I do it like that:

```
show:
/.../
    actions:
        edit: ~
```

I get missing pk exception. If I add pk like that:

```
    actions:
        edit:
          params:
            pk: AcmeObject.id
```

AcmeObject.id is passed as string to route.
