### ISSUE TITLE
formType: daterange_picker in filter not working correctly

### ISSUE THREAD

**Issue by madc** [symfony2admingenerator/AdmingeneratorGeneratorBundle#641]
It is not possible to filter a date range using the daterange_picker formType form [avocode/FormExtensions](https://github.com/avocode/FormExtensions/)

```
builders:
...
    filters:
        params:
            display: [id, status, date]
            fields:
                date:
                    formType: daterange_picker
```

The list does note show any results after using this filter.
