### ISSUE TITLE
Problem with edit label translation ?

### ISSUE THREAD

**Issue by montabou** [symfony2admingenerator/AdmingeneratorGeneratorBundle#646]
Here is an extract of my generator : 

``` yaml
params:
    i18n_catalog: messages
builders:
    show:
        params:
            actions:
                edit:
                    icon: icon-edit
                    label: action.object.edit.label
                    params:
                        pk: "{{Entity.id}}"
```

I obtain this :
![capture](https://f.cloud.github.com/assets/792812/1014972/d201ef84-0bcc-11e3-99aa-82cf324797e8.png)
If I translate `action.object.edit.label` into my `messages.fr.yml` it's ok, but I was wondering why it does not use symfony2admingenerator translation.
Is it just because custom actions are not translated with symfony2admingenerator ?
