### ISSUE TITLE
Embeded form types not working

### ISSUE THREAD

**Issue by auss** [symfony2admingenerator/AdmingeneratorGeneratorBundle#650]
Hi,

Maybe I'm doing something wrong... I need to embed one form. Here is it's generator.yml:

``` yml
generator: admingenerator.generator.propel
params:
    model: NS\CMSBundle\Model\Page\Page
    namespace_prefix: NS
    entity_manager: ~
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields:
        body1:
            addFormOptions:
                attr:
                    class: 'rich-text'
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: YourModel.title }|"
            display: [Title, body1, Body2, MetaTitle, MetaKeywords, MetaDescription, MetaPriority, IsSitemapExcluded, Type]
```

Here is the generator where I want it to be embeded:

``` yml
generator: admingenerator.generator.propel
params:
    model: NS\CatalogBundle\Model\Product\Product
    namespace_prefix: NS
    entity_manager: ~
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    embed_types:
        - "NS:AdminBundle:Page-generator.yml"
    fields:
      page:
        formType: \NS\AdminBundle\Form\Type\Page\EditType
       name:
        formType: text
        getter: getName
        dbType: LONGVARCHAR
        sortOn: product_i18n.name
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for AdminBundle
            display: [id, name, is_active, is_taxed, is_free, weight]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [name, weight, is_active, is_taxed, is_free]
    new:
        params:
            title: New object for AdminBundle
            display: [name, is_active, is_taxed, is_free, weight, servings, sold_in_qty]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the product \"%object%\"|{ %object%: Product.name }|"
            tabs:
              "Default":
                "NONE": [name, is_active, is_taxed, is_free, weight, servings, sold_in_qty]
              "CMS":
                "Content": [page]
            actions:
                save: ~
#                save-and-add: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: YourModel.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
```

I've modified Page\EditType.php according to documentation:

``` php
<?php

namespace NS\AdminBundle\Form\Type\Page;

use Admingenerated\NSAdminBundle\Form\BasePageType\EditType as BaseEditType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EditType extends BaseEditType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);
        $resolver->setDefaults(array(
                'data_class' => "\NS\CMSBundle\Model\Page\Page"
            ));
    }

    public function getName()
    {
        return 'page';
    }
}
```

And I receive error:

``` php
Could not load type "\NS\AdminBundle\Form\Type\Page\EditType"
```

Any help ? :)
