### ISSUE TITLE
Error with the action save-and-list or save-and-add

### ISSUE THREAD

**Issue by tgilbert** [symfony2admingenerator/AdmingeneratorGeneratorBundle#664]
I have problem with action save-and-list.

I use this version "cedriclombardot/admingenerator-generator-bundle": "2.2.*@dev"

If i use  save_and_list. It work's but it will not on the list.

My generator.yml

```
generator: admingenerator.generator.doctrine
params:
    model: Portail\MainBundle\Entity\Lieu
    namespace_prefix: Portail
    entity_manager: default
    bundle_name: AdminBundle
    fields:
        couleur:
            formType: genemu_jquerycolor

builders:
    list:
        params:
            title: Liste des lieux
            display: [lib, code, couleur]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [lib, code]
    new:
        params:
            title: Nouveau lieu
            display: [lib, code, couleur]
            actions:
                save: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Modification \"%object%\"|{ %object%: Lieu.code }|"
            display: [lib, code, couleur]
            actions:
                save: ~
                save-and-list: ~
                list: ~
    delete: ~
```

I have this error

```
Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Warning: strtr() expects parameter 1 to be string, array given in /home/tgilbert/Projets/myatixnet/app/bootstrap.php.cache line 237") in "EditBuilderTemplate.php.twig".
```

I also cleared the cache

Any idea
