### ISSUE TITLE
"help" option with form

### ISSUE THREAD

**Issue by denys281** [symfony2admingenerator/AdmingeneratorGeneratorBundle#683]
Few version ago, in form I can create help section for each field:

``` yml
 title:
     label: Title
     help: Some help text
```

But this isn't work now. This feature was removed?
