### ISSUE TITLE
Problems by loading routes

### ISSUE THREAD

**Issue by fadoe** [symfony2admingenerator/AdmingeneratorGeneratorBundle#698]
routing.yml:

```
FadoeCmsBundle_admin_fadoe_cms_bundle_Backend:
    resource: "@FadoeCmsBundle/Controller/Backend/"
    type: admingenerator
    prefix: /user
```

This Bundle is loaded in AppKernel.php. I can access my controller (with a other routing statement) at Fadoe/CmsBundle/Controller/IndexController.php. But when I (or the admin generator) add the lines to my routing.yml, I get the following error:

```
Cannot load resource "@FadoeCmsBundle/Controller/Backend/". Make sure the "FadoeCmsBundle" bundle is correctly registered and loaded in the application kernel class. 
```

I found out this problem occur in Admingenerator/GeneratorBundle/Routing/RoutingLoader.php on Line 143. When I comment this if statement it works fine. Symfony have a problem by resolving @FadoeCmsBundle/Controller/Backend/ and type 'annotation'.

Have anyone a idea or solution? Or is it a bug?
