### ISSUE TITLE
[Question] Embed form types with one to many relation.

### ISSUE THREAD

**Issue by denys281** [symfony2admingenerator/AdmingeneratorGeneratorBundle#699]
Hi! Is it possible to make embed form with one to many relation from the box? I try but it give me error.  

I have  Poll entity:

``` php
/**
 * Poll
 *
 * @ORM\Table(name="poll")
 * @ORM\Entity(repositoryClass="Webmil\Frontend\PollBundle\Entity\PollRepository")
 */
class Poll
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\OneToMany(targetEntity="\Webmil\Frontend\PollBundle\Entity\PollQuestion", mappedBy="poll",  cascade={"remove"})
     * 
    */
    private $pollQuestion;

}

```

And pollQiestion

``` php

/**
 * PollQuestion
 *
 * @ORM\Table(name="poll_question")
 * @ORM\Entity(repositoryClass="Webmil\Frontend\PollBundle\Entity\PollQuestionRepository")
 */
class PollQuestion
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;


    /**
    * @ORM\ManyToOne(targetEntity="Webmil\Frontend\PollBundle\Entity\Poll", inversedBy="pollQuestion")
    * @ORM\JoinColumn(name="poll_id", referencedColumnName="id", nullable=true, onDelete="CASCADE")
    * */
    private $poll;
}
```

``` yml

generator: admingenerator.generator.doctrine
params:
    model: Webmil\Frontend\PollBundle\Entity\Poll
    namespace_prefix: Webmil
    concurrency_lock: ~
    bundle_name: BackendPollBundle
    embed_types:
    - "PollQuestion-generator.yml"
    pk_requirement: ~
    fields: 
        pollQuestion:  
          formType:           \Webmil\BackendPollBundle\Form\Type\PollQuestion\EditType 
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Опросы
            display: [isActive, title]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: Опросы
            display: [isActive, title, pollQuestion]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Опрос \"%object%\"|{ %object%: Poll.title }|"
            display: [isActive, title]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Poll.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
```

EditType form:

``` php

/**
 * EditType
 */
class EditType extends BaseEditType
{

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);
        $resolver->setDefaults(array(
                'data_class' => "\Webmil\Frontend\PollBundle\Entity\PollQuestion" 
            ));
    }

    public function getName()
    {
        return 'pollQuestion';
    }
}


```

And error:

```
The form's view data is expected to be an instance of class \Webmil\Frontend\PollBundle\Entity\PollQuestion, but is an instance of class Doctrine\Common\Collections\ArrayCollection. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class Doctrine\Common\Collections\ArrayCollection to an instance of \Webmil\Frontend\PollBundle\Entity\PollQuestion. 

```

I understand that I need to write data transformer?
