### ISSUE TITLE
New option for list view: deactivate sorting

### ISSUE THREAD

**Issue by fadoe** [symfony2admingenerator/AdmingeneratorGeneratorBundle#716]
Sometimes we don't want to sort a column in list view. It would be great if there is a parameter in generator.yml to deactivate the sorting of a column:

```
builders:
    list:
        fields:
            my_field:
                 is_sortable: false
```
