### ISSUE TITLE
Can't add translation_domain to form field

### ISSUE THREAD

**Issue by fadoe** [symfony2admingenerator/AdmingeneratorGeneratorBundle#720]
I try to add the translation domain to a form field:

```
params:
    fields:
        moduleName:
            formType: entity
            addFormOptions:
                class: MyBundle:MyEntity
                property: myProperty
                translation_domain: MyTranslationDomain
```

But the generated form type add always 'translation_domain' => 'Admin'. Is this a bug or is that intentional?
