### ISSUE TITLE
ManytoMany on filter

### ISSUE THREAD

**Issue by tgilbert** [symfony2admingenerator/AdmingeneratorGeneratorBundle#723]
Hi,

I try to use a relation ManyToMany into a filter, but i have a error.

My schema : 
  Enseigne <=> Professeur

If i use in the filter the field enseignements, I can see all enseignements list.
When i filter by enseignement. I 've got this error

```
FatalErrorException: Error: Call to undefined method Doctrine\Common\Collections\ArrayCollection::getId() in /home/tgilbert/Projets/bag/app/cache/dev/Admingenerated/AtixBagBundle/BaseProfesseurController/ListController.php line 184 
```

Enseignement.php

```
  /**
 * @var \Doctrine\Common\Collections\Collection
 * @ORM\ManyToMany(targetEntity="Professeur", inversedBy="enseignements")
 * @ORM\JoinTable(name="professeur_enseigne",
 *   joinColumns={
 *     @ORM\JoinColumn(name="enseignement_id", referencedColumnName="id")
 *   },
 *   inverseJoinColumns={
 *     @ORM\JoinColumn(name="professeur_id", referencedColumnName="id")
 *   }
 * )
 */
private $professeurs;
```

Professeur.php

```
/**
 * @var \Doctrine\Common\Collections\Collection
 *
 * @ORM\ManyToMany(targetEntity="Enseignement", mappedBy="professeurs")
 */
private $enseignements;
```

Against by the addition and edition of these fields works fine

My config : 

```
generator: admingenerator.generator.doctrine
params:
    model: Atix\BagBundle\Entity\Professeur
    namespace_prefix: Atix
    concurrency_lock: ~
    bundle_name: BagBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Liste des professeurs
            display: [nom, prenom, enseignements]
            max_per_page: 60
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [nom, utilisateur, enseignements]
    new:
        params:
            title: Nouveau professeur
            display: [nom, prenom, utilisateur]
            actions:
                save: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "modification de : \"%object%\"|{ %object%: Professeur }|"
            display: [nom, prenom, civilite, utilisateur, enseignements]
            actions:
                save: ~
                save-and-list: ~
                list: ~
    show:
        params:
            title: "modification de : \"%object%\"|{ %object%: Professeur }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
```

Is that there has already had to issue ManyToMany ?

Thanks
