### ISSUE TITLE
What other object_actions are available?

### ISSUE THREAD

**Issue by davidangel** [symfony2admingenerator/AdmingeneratorGeneratorBundle#733]
Using the generator.yml files to set up my project, wondering what other options exist under object_actions:

```
builders:
  list:
    params:
        title: Clients List
        display: [ name_full, flag_disabled ]
        actions:
            new: ~
        object_actions:
            show: ~
            edit: ~
            delete: ~
```

Please advise :-)
