### ISSUE TITLE
?stop_loop=true If you're in prod try cache:warmup

### ISSUE THREAD

**Issue by hd-deman** [symfony2admingenerator/AdmingeneratorGeneratorBundle#74]
I have the following structure
![bundle structure](http://uploadr.obnovlenie.ru/uploads/dmitry.tsoy-2012-01-16-190420.png)

and following generator.yml 

``` yml
generator: admingenerator.generator.doctrine
params:
  model: Acme\Lacroco\StoreBundle\Entity\MltdCategory
  namespace_prefix: Acme
  subfolder: LacrocoBackend
  bundle_name: AcmeLacrocoBackendStoreBundle
  fields: ~
```

when trying to access the url i get this error with reddirect to url with param ?stop_loop=true

```
Opps an error occurred in your configuration. If you're in prod try cache:warmup
```
