### ISSUE TITLE
Namespace generation problem

### ISSUE THREAD

**Issue by maxailloud** [symfony2admingenerator/AdmingeneratorGeneratorBundle#76]
Hi,

I'm failing using the bundle.

I got the message:

```
Opps an error occurred in your configuration. If you're in prod try cache:warmup
```

The problem is I'm in dev environment and the generate classes are wrong.

See, my bundle tree folder:
- src
  - Billy
    - BlogBundle
    - BlogBundle.php

My generator.yml file:

``` yaml
generator: admingenerator.generator.propel
params:
  model: Billy\BlogBundle\Model\Post
  namespace_prefix: Billy
  bundle_name: BlogBundle
  fields: ~

builders:
  list:
    params:
      title: List for BlogBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New object for BlogBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ Post.title }}"
      display: ~
      actions:
        list: ~
  delete: ~
```

And my routing file is:

``` yaml
BlogBundle_admin_billy_blog_bundle_post:
    resource: "@BlogBundle/Controller/Post/"
    type:     admingenerator
    prefix:   /admin/billy_blog_bundle/post

BlogBundle:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /
```

When I look up in the cache directory I go this:
- cache
  - Admingenerated
    - BillyBlogBundle
      - BasePostController
      - Form
      - Resources
    - BlogBundle
      - BasePostController

Why 2 directories ? And why BillyBlogBundle directory as my bundle namespace is Billy\BlogBundle and my bundle name BlogBundle ?

Maybe I made something wrong but I didn't see what.
