### ISSUE TITLE
afe_date_picker format and List builder

### ISSUE THREAD

**Issue by enkaho** [symfony2admingenerator/AdmingeneratorGeneratorBundle#764]
Hi,

First of all, I want to thanks you guys for this huge and awesome generator !

I'm using now avocode/FormExtensions, and i want to format date field rendering in edit form wiith this widget.

In the generator.yml : 

```
fields: 
        start:
            formType: afe_date_picker
            addFormOptions:
                format: dd-MM-yyyy
```

I have an issue with list builder and the date format for my start field.
Indeed, afe_date_picker format and php date format are not the same...
afe_date_picker with format: dd-MM-yyyy  rendering 20-06-2014 and in the list builder view this format rendering 0606-JunJun-14141414

How can i resolve this ?

Thx for your support.
