### ISSUE TITLE
Set a global listener

### ISSUE THREAD

**Issue by mirza99** [symfony2admingenerator/AdmingeneratorGeneratorBundle#778]
Hi, I have created a listener but the preUpdate() method is not called. 

In the EditController the method saveObject() calls : $em->persist($Contact);

So, the prePersist should be called but, it isn't and even the post method aren't called

The config looks like this :

``` yaml
my.objectlistener:
        class: Acme\DemoBundle\Listener\ObjectListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
```

What should I do ?
