### ISSUE TITLE
Filter : Use same entity in two distinct fields

### ISSUE THREAD

**Issue by rpostolov** [symfony2admingenerator/AdmingeneratorGeneratorBundle#780]
Hi,

I use two entities (Lieu and Session) with ManyToMany relation.

So, when i edit Session's entity i have double liste for the entity 'Lieu' (afe_double_liste_entity) that is perfect.

But in the filter i don't want double liste, i wnat a single list. There is my question, in the session-admingenerator.yml how can i declare the same entity in double liste and in the same time single liste ?

hiere is my configuration of session-admingenerator.yml :

```
fields:
      lieux:
        label:   Location
        formType: afe_double_list_entity
```

Thanks for help.
