### ISSUE TITLE
None of my actions are showing up

### ISSUE THREAD

**Issue by yacreo** [symfony2admingenerator/AdmingeneratorGeneratorBundle#785]
My actions are not being renderred. When I inspect my code(FF) I get this empty block.
![screen shot 2014-08-27 at 13 36 41](https://cloud.githubusercontent.com/assets/1264719/4058460/3f04e0d8-2dd6-11e4-846b-b2fd16330f1d.png)

Here is my generator.yml. Im using symfoy2.5 and dev-master of symfony2admingenerator and cie updated as today. I dont know what I've missed. 
Any help? Thanks!

``` yaml
generator: admingenerator.generator.doctrine
params:
    model: Infrastructure\LocationBundle\Entity\UserProfile
    namespace_prefix: Infrastructure
    concurrency_lock: ~
    bundle_name: LocationBundle
    embed_types:
    # short syntax
        - "FamilyMember-generator.yml"
    pk_requirement: ~
    fields:
        username:
            label: username.label
            addFormOptions:
                read_only: true
        email:
            label: email.label
            addFormOptions:
                read_only: true
        firstName:
            label: firstname.label
        lastName:
            label: lastname.label
        birthDate:
            label: birthdate.label
            formType: s2a_date_picker
        sex:
            label: sex.label
            formType: s2a_select2_choice
            addFormOptions:
                choices:
                    'female': Female
                    'male': Male
        position:
            label: position.label
        department:
            label: department.label
            formType: s2a_select2_choice
            addFormOptions:
                choices:
                    'die': Infrastructure & Energy
                    'dea': Economic Affairs
                    'drea': Rural Economy & Agriculture
        address:
            label: address.label
        longitude:
            label: longitude.label
        latitude:
            label: latitude.label
        phoneNumber:
            label: phonenumber.label
        enabled:
            label: enabled.label
            addFormOptions:
                read_only: true
       # roles:
       #     label: roles.label
       #     formType: collection_table

        familyMember:
            label:            familymember.label
            #dbType:           collection
            formType:         s2a_collection_table
            addFormOptions:
                #widget:         fieldset
                # use generated embed type
                type:           \Infrastructure\LocationBundle\Form\Type\FamilyMember\NewType
                allow_add:      true
                allow_delete:   true
                by_reference:   false
                options:
                    label:          familymember.label
                    data_class:     Infrastructure\LocationBundle\Entity\FamilyMember
builders:
    list:
        params:
            title: List of UserProfile
            display: [username,email,firstName,lastName,birthDate,position,department,address,longitude,latitude,phoneNumber]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New User
            display: [username,email,firstName,lastName,birthDate,sex,position,department,address,longitude,latitude,phoneNumber,familyMember]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the User \"%username%\"|{ %username%: UserProfile.username }|"
            display: [username,email,firstName,lastName,birthDate,sex,position,department,address,longitude,latitude,phoneNumber,familyMember]
            actions:
                save: ~                
                save-and-add: ~
                save-and-list: ~
                list: ~
    show:
        params:
            title: "You're viewing the User \"%firstname% %lastname%\"|{ %firstname%: UserProfile.firstname, %lastname%: UserProfile.lastname }|"
            display: [username,email,firstName,lastName,birthDate,sex,position,department,address,longitude,latitude,phoneNumber,familyMember]
            actions:
                list: ~
                edit: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
```
