### ISSUE TITLE
 Doctrine ORM Manager named "default" does not exist.

### ISSUE THREAD

**Issue by ndoulgeridis** [symfony2admingenerator/AdmingeneratorGeneratorBundle#806]
Hello,

I have multiple entity managers I have a generator which has a field

```
  category:
    label: field.category
    getter: category.name
    formType: entity
```

When i load the page I get this error:

 Doctrine ORM Manager named "default" does not exist.

I haven't found a way in new docs to add em or entity manager to generator. How can i change default to the right one?
