### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by enkaho** [symfony2admingenerator/AdmingeneratorGeneratorBundle#835]
Hi, 

I can't display filters on List.
my xxx-generator.yml :

```
builders:
    list:
        params:
            title: List for TestBundle
            display: [ mail, username, enabled ]
            filters:    
                display: [ mail ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
```

composer.json :

```
"symfony2admingenerator/generator-bundle": "^2.0@beta",
 "symfony/symfony": "^2.7",
```
