### ISSUE TITLE
doctrine virtual file field type

### ISSUE THREAD

**Issue by baym** [symfony2admingenerator/AdmingeneratorGeneratorBundle#90]
Hi...  I'm working with doctrine and try to implement the file uploading. I follow the intructions, how to implement own field, but always get the same error while rendering the form:

> An exception has been thrown during the rendering of a template ("The dbType "virtual" is only for list implemented (column "file")") in ../CommonAdmin/EditTemplate/fieldset.php.twig at line 11.

I used such configuration for creating form fields:

``` yaml
new:
  fields:
    file:
      formType: file
      formOptions: []
```
